// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX14
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX14PackageString = "fc370c04-8f50-4dd7-ad75-0b4842bf9ba2";
        public static Guid guidVSIX14Package = new Guid(guidVSIX14PackageString);

        public const string guidVSIX14PackageCmdSetString = "90c0bbcf-f755-486a-8999-f8602281996e";
        public static Guid guidVSIX14PackageCmdSet = new Guid(guidVSIX14PackageCmdSetString);

        public const string guidImagesString = "e77df50b-cba4-4e37-aced-52166f9f6fec";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}