// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX37
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX37PackageString = "58c8934f-c4cc-4832-8c80-429e12c4b9a7";
        public static Guid guidVSIX37Package = new Guid(guidVSIX37PackageString);

        public const string guidVSIX37PackageCmdSetString = "d76b171b-f1df-4dbc-9956-e860636d1ae2";
        public static Guid guidVSIX37PackageCmdSet = new Guid(guidVSIX37PackageCmdSetString);

        public const string guidImagesString = "df304868-63cd-4f29-a05b-8bf0d0d66f18";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int OutPutWindow1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}