// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX18
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX18PackageString = "1438e381-bd44-47c0-9233-ade7eec9fcb9";
        public static Guid guidVSIX18Package = new Guid(guidVSIX18PackageString);

        public const string guidVSIX18PackageCmdSetString = "957783e4-1885-44c5-a335-8854fa0e38fa";
        public static Guid guidVSIX18PackageCmdSet = new Guid(guidVSIX18PackageCmdSetString);

        public const string guidImagesString = "f5fd6044-55f9-44fe-8e01-f1207636ad1b";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "ad359478-3d59-4151-867c-2cc9ad4dcaef";
        public static Guid guidImages1 = new Guid(guidImages1String);

        public const string guidImages2String = "43c2f66c-fa6e-4cba-850e-e100e027b0db";
        public static Guid guidImages2 = new Guid(guidImages2String);

        public const string guidImages3String = "6c746930-411e-46c4-b495-16aaee845301";
        public static Guid guidImages3 = new Guid(guidImages3String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int cmdidCommand2 = 0x1021;
        public const int cmdidCommand3 = 0x1022;
        public const int cmdidCommand4 = 0x1023;
        public const int MyMenuGroup1 = 0x2021;
        public const int MyMenu = 0x2022;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
       
    }
}