// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX15
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX15PackageString = "a3b38abb-6000-4dc6-91b3-925ff57799dd";
        public static Guid guidVSIX15Package = new Guid(guidVSIX15PackageString);

        public const string guidVSIX15PackageCmdSetString = "9a9f54d2-caca-4df5-b9c2-afedd6b99890";
        public static Guid guidVSIX15PackageCmdSet = new Guid(guidVSIX15PackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int cmdidCommand2 = 0x1021;
        public const int MyMenuGroup1 = 0x1234;
        public const int cmdidCommand3 = 0x1022;
        public const int cmdidCommand4 = 0x1023;
    }
}