// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX40
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX40PackageString = "f62ca1ce-3797-47b5-88af-ceffd7fa28b2";
        public static Guid guidVSIX40Package = new Guid(guidVSIX40PackageString);

        public const string guidVSIX40PackageCmdSetString = "6cbb2de4-5513-4f3e-8868-241ea09eb0e6";
        public static Guid guidVSIX40PackageCmdSet = new Guid(guidVSIX40PackageCmdSetString);

        public const string guidImagesString = "6ff0137e-b7ce-4795-9ef3-86b9b0eefbe8";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}