// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX11
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIX11.501be57f-3c64-4a7c-9ef9-449ff65095d9";
        public const string Name = "VSIX11";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "zh-CN";
        public const string Version = "2.0";
        public const string Author = "Zmrbak";
        public const string Tags = "tags,tags2";
    }
}
