// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX11
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX11PackageString = "d586908b-9380-484f-9348-47d8be2a63c8";
        public static Guid guidVSIX11Package = new Guid(guidVSIX11PackageString);

        public const string guidVSIX11PackageCmdSetString = "99e63284-c65c-4cb8-b2bf-013a40cb998f";
        public static Guid guidVSIX11PackageCmdSet = new Guid(guidVSIX11PackageCmdSetString);

        public const string guidImagesString = "9c766b46-8207-468c-a1fe-7fdf851ba3fc";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}