// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

namespace VSIX11A
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIX11A.c4833818-4054-4979-b3f4-b5d6b019c28e";
        public const string Name = "VSIX11A";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Zmrbak";
        public const string Tags = "";
    }
}
