// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX19
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX19PackageString = "c3a3981e-5dd1-48b2-b0c9-66c3ca41f3a9";
        public static Guid guidVSIX19Package = new Guid(guidVSIX19PackageString);

        public const string guidVSIX19PackageCmdSetString = "42157b7b-bce8-43fd-ab56-49dbc3cabdf6";
        public static Guid guidVSIX19PackageCmdSet = new Guid(guidVSIX19PackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0200;
        public const int MyMenu = 0x0101;
        public const int MRUGroup = 0x0102;
    }
}