// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX21
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX21PackageString = "59534696-90fe-463d-a838-64b8c241c306";
        public static Guid guidVSIX21Package = new Guid(guidVSIX21PackageString);

        public const string guidVSIX21PackageCmdSetString = "b8e59dbf-c048-4017-a631-b154a6e4074e";
        public static Guid guidVSIX21PackageCmdSet = new Guid(guidVSIX21PackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int cmdidCommand2 = 0x1021;
    }
}