// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX36
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX36PackageString = "e2665804-f261-4b78-8891-7f6311dd9439";
        public static Guid guidVSIX36Package = new Guid(guidVSIX36PackageString);

        public const string guidVSIX36PackageCmdSetString = "82569999-4dc4-470b-b180-fca79a4c8156";
        public static Guid guidVSIX36PackageCmdSet = new Guid(guidVSIX36PackageCmdSetString);

        public const string guidImagesString = "9e184fca-64ed-4461-94e3-03bfc0fd4297";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}