// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX33
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX33PackageString = "fa5417f0-c19c-435a-923b-b0d8e0df9b20";
        public static Guid guidVSIX33Package = new Guid(guidVSIX33PackageString);

        public const string guidVSIX33PackageCmdSetString = "1330f7a8-a988-4836-95e8-b5932bdf1a78";
        public static Guid guidVSIX33PackageCmdSet = new Guid(guidVSIX33PackageCmdSetString);

        public const string guidImagesString = "2369a052-312b-4b14-8922-ecec72f59f8d";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}