// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX17
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX17PackageString = "1d7d77bc-f35a-49f6-843b-e38c3aca77e9";
        public static Guid guidVSIX17Package = new Guid(guidVSIX17PackageString);

        public const string guidVSIX17PackageCmdSetString = "49e98d96-12e7-4f0d-bddf-71a6cdd02743";
        public static Guid guidVSIX17PackageCmdSet = new Guid(guidVSIX17PackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int Command1Id_1 = 0x0123;
        public const int MyMenu = 0x0124;
        public const int MyMenuGroup_1 = 0x0125;
        public const int Command1Id_2 = 0x0126;
        public const int Command1Id_3 = 0x0127;
        public const int Command1Id_4 = 0x0128;
        public const int MyMenu1 = 0x0129;
        public const int MyMenuGroup_2 = 0x0130;
        public const int Command1Id_5 = 0x0131;
    }
}