// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIX32
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIX32PackageString = "82d97593-3578-413c-8fb8-50794380220c";
        public static Guid guidVSIX32Package = new Guid(guidVSIX32PackageString);

        public const string guidVSIX32PackageCmdSetString = "7595b6d9-dc0b-41ce-98f0-a23e949d39b3";
        public static Guid guidVSIX32PackageCmdSet = new Guid(guidVSIX32PackageCmdSetString);

        public const string guidImagesString = "379b2954-cc97-491b-8c63-afdddac9aa4e";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int MyMenu = 0x0101;
        public const int MyGroup = 0x0102;
        public const int Button1 = 0x0103;
        public const int Button2 = 0x0104;
        public const int Button3 = 0x0105;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}